version: "3.8"
services:
  ubuntu-desktop:
    container_name: ubuntu-desktop-container
    image: mscrnt/ubuntu-desktop:gpu
    environment:
      - TZ=
      - HOST_OS=
      - HOST_HOSTNAME=
      - HOST_CONTAINERNAME=ubuntu-desktop-container
      - NVIDIA_VISIBLE_DEVICES=
      - NVIDIA_DRIVER_CAPABILITIES=
      - USER=
      - PASSWORD=
      - VNCPASSWORD=
    ports:
      - "22:22"
      - "5901:5901"
      - "3389:3389"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
