version: "3.8"
services:
  ubuntu-desktop:
    container_name: ubuntu-desktop-headless
    image: mscrnt/ubuntu-desktop:headless
    environment:
      - USER=
      - PASSWORD=
      - VNCPASSWORD=
      - ENABLE_X2GO=
      - ENABLE_VNC=
      - ENABLE_XRDP=
    ports:
      - "22:22"
      - "5901:5901"
      - "3389:3389"