version: '3.8'
services:
  ubuntu-desktop:
    image: mscrnt/ubuntu-desktop:latest
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ports:
      - "5901:5901"
      - "3389:3389"
      - "22:22"
    environment:
      USER: <USERNAME>
      PASSWORD: <PASSWORD>
      VNCPASSWORD: <VNCPASSWORD>
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]